paths:
  data: data

silver:
  divipola_dir: data/silver/divipola
  divipola_file: divipola.parquet

  subregiones_dir: data/silver/subregiones
  subregiones_file: subregiones_nacional.parquet

  departamentos_dir: data/silver/departamentos
  departamentos_file: departamentos.parquet

  pme_dir : data/silver/pmenfoquediferencial
  pme_sex_p_file : pme_sexopoblacion.csv
  pme_sex_h_file : pme_sexojefehogar.csv



data_silver:
  columns:
    divipola:
      id_mun: MpCodigo
      name_mun: MpNombre
      id_dept: departamentos — Departamentos_Diciembre_2025_shp/Depto.shp_DeCodigo
      geometry: geometry

    departamentos:
      id_dept: DeCodigo
      name_dept: DeNombre
      geometry: geometry