mortalidad_desnutricion:
  last_incremental_value: mortalidad_desnutricion_run_20260505_163431.csv
  incremental_column: run_filename
  last_run_at: '2026-05-05T21:34:34.198666+00:00'
  last_row_count: 285
  extraction_mode: db_load_gold_run
subregion:
  last_incremental_value: '9900'
  incremental_column: id_subregion
  last_run_at: '2026-04-01T01:04:54.459400+00:00'
  last_row_count: 141
  extraction_mode: db_load_geo_parquet
perfil_antioquia:
  last_incremental_value: perfil_antioquia_run_2026_03_28.csv
  incremental_column: run_filename
  last_run_at: '2026-04-05T16:20:17.002504+00:00'
  last_row_count: 18
  extraction_mode: db_load_gold_run
divipola:
  last_incremental_value: '99773'
  incremental_column: id_mun
  last_run_at: '2026-04-09T16:34:17.028016+00:00'
  last_row_count: 1123
  extraction_mode: db_load
victimas_golden_load:
  last_incremental_value: victimas_run_20260414_172611.parquet
  incremental_column: file_name
  last_run_at: '2026-04-16T20:01:52.033031+00:00'
  last_row_count: 81156
  extraction_mode: golden_load
pme_jefe_hogar_load:
  last_incremental_value: pme_jefe_hogar_run_20260530_193724.parquet
  incremental_column: file_name
  last_run_at: '2026-04-17T18:16:02.040935+00:00'
  last_row_count: 192
  extraction_mode: golden_load
pme_por_genero_load:
  last_incremental_value: pme_por_genero_run_20260325_193724..parquet
  incremental_column: file_name
  last_run_at: '2026-04-17T18:41:51.611788+00:00'
  last_row_count: 192
  extraction_mode: golden_load
beneficiarios_iraca_load:
  last_incremental_value: beneficiarios_iraca_run_20260429_182435.parquet
  incremental_column: file_name
  last_run_at: '2026-04-29T18:24:37.539647+00:00'
  last_row_count: 563
  extraction_mode: golden_load
departamentos:
  last_incremental_value: '99'
  incremental_column: id_dept
  last_run_at: '2026-05-02T16:42:46.161421+00:00'
  last_row_count: 33
  extraction_mode: db_load
red_vial:
  last_incremental_value: P.D.
  incremental_column: id_road
  last_run_at: '2026-04-20T16:21:23.689162+00:00'
  last_row_count: 313
  extraction_mode: db_load
poblacion_load:
  last_incremental_value: poblacion_run_20260325_193724.parquet
  incremental_column: file_name
  last_run_at: '2026-04-21T13:50:12.029704+00:00'
  last_row_count: 25346
  extraction_mode: golden_load
mun_pdet_load:
  last_incremental_value: mun_pdet_run_20260421_202413.parquet
  incremental_column: file_name
  last_run_at: '2026-05-02T16:58:12.805527+00:00'
  last_row_count: 170
  extraction_mode: golden_load
erradicacion_cultivos_load:
  last_incremental_value: erradicacion_cultivos_run_20260429_181434.parquet
  incremental_column: file_name
  last_run_at: '2026-04-29T18:18:00.104907+00:00'
  last_row_count: 3987
  extraction_mode: golden_load
resguardo_indigena_load:
  last_incremental_value: resguardo_indigena_run_20260421_202413.parquet
  incremental_column: file_name
  last_run_at: '2026-04-22T18:04:07.925694+00:00'
  last_row_count: 959
  extraction_mode: golden_load
mercados_campesinos_load:
  last_incremental_value: mercados_campesinos_run_20260504_115631.parquet
  incremental_column: file_name
  last_run_at: '2026-05-04T16:56:33.250785+00:00'
  last_row_count: 45
  extraction_mode: golden_load
produc_petroleo_load:
  last_incremental_value: produc_petroleo_run_20260429_211557.parquet
  incremental_column: file_name
  last_run_at: '2026-04-30T21:38:23.814980+00:00'
  last_row_count: 4638
  extraction_mode: golden_load
produc_gas_load:
  last_incremental_value: produc_gas_run_20260430_204826.parquet
  incremental_column: file_name
  last_run_at: '2026-04-30T21:32:53.514031+00:00'
  last_row_count: 4902
  extraction_mode: golden_load
regalias_load:
  last_incremental_value: regalias_run_20260430_200536.parquet
  incremental_column: file_name
  last_run_at: '2026-04-30T20:08:24.281993+00:00'
  last_row_count: 6173
  extraction_mode: golden_load
minerales_load:
  last_incremental_value: minerales_run_20260429_203718.parquet
  incremental_column: file_name
  last_run_at: '2026-04-29T20:37:56.411797+00:00'
  last_row_count: 22845
  extraction_mode: golden_load
edu_superior_load:
  last_incremental_value: edu_superior_run_20260429_183230.parquet
  incremental_column: file_name
  last_run_at: '2026-04-29T18:32:31.304194+00:00'
  last_row_count: 9688
  extraction_mode: golden_load
edu_escolar_load:
  last_incremental_value: edu_escolar_run_20260426_000811.parquet
  incremental_column: file_name
  last_run_at: '2026-04-26T20:55:19.955690+00:00'
  last_row_count: 6721
  extraction_mode: golden_load
mercado_laboral_load:
  last_incremental_value: mercado_laboral_run_20260503_124754.parquet
  incremental_column: file_name
  last_run_at: '2026-05-03T17:48:23.306573+00:00'
  last_row_count: 26328
  extraction_mode: golden_load
desnutricion_aguda_5:
  last_incremental_value: desnutricion_aguda_5_run_20260504_112715.csv
  incremental_column: run_filename
  last_run_at: '2026-05-04T16:27:33.291795+00:00'
  last_row_count: 11339
  extraction_mode: db_load_gold_run
bajo_peso_nacer_load:
  last_incremental_value: bajo_peso_nacer_run_Datos_2019_110.parquet
  incremental_column: file_name
  last_run_at: '2026-05-06T16:31:42.665862+00:00'
  last_row_count: 5742
  extraction_mode: golden_load
