mortalidad_desnutricion:
  last_incremental_value: mortalidad_desnutricion_run_20260520_124201.csv
  incremental_column: run_filename
  last_run_at: '2026-05-20T17:42:03.961291+00:00'
  last_row_count: 168
  extraction_mode: db_load_gold_run
subregion:
  last_incremental_value: '9900'
  incremental_column: id_subregion
  last_run_at: '2026-04-01T01:04:54.459400+00:00'
  last_row_count: 141
  extraction_mode: db_load_geo_parquet
perfil_antioquia:
  last_incremental_value: Perfil_antioquia_run_20260520_125653.csv
  incremental_column: run_filename
  last_run_at: '2026-05-20T17:56:55.410719+00:00'
  last_row_count: 18
  extraction_mode: db_load_gold_run
divipola:
  last_incremental_value: '99773'
  incremental_column: id_mun
  last_run_at: '2026-05-19T21:24:20.662228+00:00'
  last_row_count: 1123
  extraction_mode: db_load
victimas_golden_load:
  last_incremental_value: victimas_run_20260414_172611.parquet
  incremental_column: file_name
  last_run_at: '2026-04-16T20:01:52.033031+00:00'
  last_row_count: 81156
  extraction_mode: golden_load
pme_jefe_hogar_load:
  last_incremental_value: pme_jefe_hogar_run_20260530_193724.parquet
  incremental_column: file_name
  last_run_at: '2026-04-17T18:16:02.040935+00:00'
  last_row_count: 192
  extraction_mode: golden_load
pme_por_genero_load:
  last_incremental_value: pme_por_genero_run_20260325_193724..parquet
  incremental_column: file_name
  last_run_at: '2026-04-17T18:41:51.611788+00:00'
  last_row_count: 192
  extraction_mode: golden_load
beneficiarios_iraca_load:
  last_incremental_value: beneficiarios_iraca_run_20260429_182435.parquet
  incremental_column: file_name
  last_run_at: '2026-04-29T18:24:37.539647+00:00'
  last_row_count: 563
  extraction_mode: golden_load
departamentos:
  last_incremental_value: '99'
  incremental_column: id_dept
  last_run_at: '2026-05-02T16:42:46.161421+00:00'
  last_row_count: 33
  extraction_mode: db_load
red_vial:
  last_incremental_value: P.D.
  incremental_column: id_road
  last_run_at: '2026-04-20T16:21:23.689162+00:00'
  last_row_count: 313
  extraction_mode: db_load
poblacion_load:
  last_incremental_value: poblacion_run_20260520_155038.parquet
  incremental_column: file_name
  last_run_at: '2026-05-20T20:52:51.183103+00:00'
  last_row_count: 25346
  extraction_mode: golden_load
mun_pdet_load:
  last_incremental_value: mun_pdet_run_20260421_202413.parquet
  incremental_column: file_name
  last_run_at: '2026-05-02T16:58:12.805527+00:00'
  last_row_count: 170
  extraction_mode: golden_load
erradicacion_cultivos_load:
  last_incremental_value: erradicacion_cultivos_run_20260429_181434.parquet
  incremental_column: file_name
  last_run_at: '2026-04-29T18:18:00.104907+00:00'
  last_row_count: 3987
  extraction_mode: golden_load
resguardo_indigena_load:
  last_incremental_value: resguardo_indigena_run_20260421_202413.parquet
  incremental_column: file_name
  last_run_at: '2026-04-22T18:04:07.925694+00:00'
  last_row_count: 959
  extraction_mode: golden_load
mercados_campesinos_load:
  last_incremental_value: mercados_campesinos_run_20260520_123705.parquet
  incremental_column: file_name
  last_run_at: '2026-05-20T17:37:08.971246+00:00'
  last_row_count: 45
  extraction_mode: golden_load
produc_petroleo_load:
  last_incremental_value: produc_petroleo_run_20260520_211616.parquet
  incremental_column: file_name
  last_run_at: '2026-05-20T21:16:22.720145+00:00'
  last_row_count: 1102
  extraction_mode: golden_load
produc_gas_load:
  last_incremental_value: produc_gas_run_20260520_212601.parquet
  incremental_column: file_name
  last_run_at: '2026-05-20T21:26:06.026977+00:00'
  last_row_count: 1282
  extraction_mode: golden_load
regalias_load:
  last_incremental_value: regalias_run_20260520_215207.parquet
  incremental_column: file_name
  last_run_at: '2026-05-20T21:52:28.587092+00:00'
  last_row_count: 3443
  extraction_mode: golden_load
minerales_load:
  last_incremental_value: minerales_run_20260520_214217.parquet
  incremental_column: file_name
  last_run_at: '2026-05-20T21:42:25.987530+00:00'
  last_row_count: 540
  extraction_mode: golden_load
edu_superior_load:
  last_incremental_value: edu_superior_run_20260429_183230.parquet
  incremental_column: file_name
  last_run_at: '2026-04-29T18:32:31.304194+00:00'
  last_row_count: 9688
  extraction_mode: golden_load
edu_escolar_load:
  last_incremental_value: edu_escolar_run_20260426_000811.parquet
  incremental_column: file_name
  last_run_at: '2026-04-26T20:55:19.955690+00:00'
  last_row_count: 6721
  extraction_mode: golden_load
mercado_laboral_load:
  last_incremental_value: mercado_laboral_run_20260520_123119.parquet
  incremental_column: file_name
  last_run_at: '2026-05-20T17:31:47.043648+00:00'
  last_row_count: 26328
  extraction_mode: golden_load
desnutricion_aguda_5:
  last_incremental_value: desnutricion_aguda_5_run_20260520_122924.csv
  incremental_column: run_filename
  last_run_at: '2026-05-20T17:29:43.311939+00:00'
  last_row_count: 4420
  extraction_mode: db_load_gold_run
bajo_peso_nacer_load:
  last_incremental_value: bajo_peso_nacer_run_20260519_095057.parquet
  incremental_column: file_name
  last_run_at: '2026-05-19T14:51:04.909752+00:00'
  last_row_count: 6686
  extraction_mode: golden_load
censo_load:
  last_incremental_value: censo_equino_2023.parquet
  incremental_column: file_name
  last_run_at: '2026-05-19T15:55:06.269436+00:00'
  last_row_count: 1121
  extraction_mode: golden_load
irca_load:
  last_incremental_value: irca_run_20260519_000021.parquet
  incremental_column: file_name
  last_run_at: '2026-05-19T00:20:14.879711+00:00'
  last_row_count: 18591
  extraction_mode: golden_load
