resguardo_indigena_transform:

  source:
    bronze_dir: "data/bronze/resguardo_indigena"
    silver_fact_dir: "data/silver/resguardo_indigena"
    golden_fact_dir: "data/golden/resguardo_indigena"
    dimension_dir: Null
  run:
    process_latest_run_only: true

  validation:
    required_columns:
      - 

  typing:
    numeric_columns:

    text_columns:
      - 
  

  dimensions:
    gender_type:
      file_name: 

  fact_table:
 
    file_prefix: "resguardo_indigena"